// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRecord(ctx context.Context, id int64) (Record, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListRecords(ctx context.Context, arg ListRecordsParams) ([]Record, error)
}

var _ Querier = (*Queries)(nil)
